export const GET_POSTS_REQUEST_SEND="GET_POSTS_REQUEST_SEND"
export const GET_POSTS_REQUEST_SUCCESS="GET_POSTS_REQUEST_SUCCESS"
export const GET_POSTS_REQUEST_FAILED="GET_POSTS_REQUEST_FAILED"

export const ADD_COMMENT_REQUEST="ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILED="ADD_COMMENT_FAILED"

export const CREATE_POST_REQUEST="CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS"
export const CREATE_POST_FAILED="CREATE_POST_FAILED"


export const LOGIN_REQUEST_SEND="LOGIN_REQUEST_SEND"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const LOGOUT="LOGOUT"

export const REGISTER_REQUEST_SEND="REGISTER_REQUEST_SEND"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"
export const RESET_REGISTER_ALERTS="RESET_REGISTER_ALERTS"

export const GET_USERS_REQUEST="GET_USERS_REQUEST"
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_FAILED="GET_USERS_FAILED"
export const SEARCH_USER="SEARCH_USER"


export const LIKE_REQUEST_SEND="LIKE_REQUEST_SEND"
export const LIKE_SUCCESS="LIKE_SUCCESS"
export const LIKE_FAILURE="LIKE_FAILURE"

export const USER_DETAILS_REQUEST="USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS="USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAILED="USER_DETAILS_FAILED"
export const USER_DETAILS_RESET="USER_DETAILS_RESET"

export const SHOW_PROFILE_REQUEST="SHOW_PROFILE_REQUEST"
export const SHOW_PROFILE_SUCCESS="SHOW_PROFILE_SUCCESS"
export const SHOW_PROFILE_FAILED="SHOW_PROFILE_FAILED"
export const SHOW_PROFILE_RESET="SHOW_PROFILE_RESET"


export const USER_DETAILS_UPDATE_REQUEST="USER_DETAILS_UPDATE_REQUEST"
export const USER_DETAILS_UPDATE_SUCCESS="USER_DETAILS_UPDATE_SUCCESS"
export const USER_DETAILS_UPDATE_FAILED="USER_DETAILS_UPDATE_FAILED"
export const RESET_UPDATE_ALERTS="RESET_UPDATE_ALERTS"

export const FOLLOW_REQUEST_SEND="FOLLOW_REQUEST_SEND"
export const FOLLOW_REQUEST_SUCCESS="FOLLOW_REQUEST_SUCCESS"
export const FOLLOW_REQUEST_FAILED="FOLLOW_REQUEST_FAILED"

export const UNFOLLOW_REQUEST_SEND="UNFOLLOW_REQUEST_SEND"
export const UNFOLLOW_REQUEST_SUCCESS="UNFOLLOW_REQUEST_SUCCESS"
export const UNFOLLOW_REQUEST_FAILED="UNFOLLOW_REQUEST_FAILED"

export const GET_FOLLOWERS_REQUEST="GET_FOLLOWERS_REQUEST"
export const GET_FOLLOWERS_SUCCESS="GET_FOLLOWERS_SUCCESS"
export const GET_FOLLOWERS_FAILED="GET_FOLLOWERS_FAILED"

/*export const GET_FOLLOWING_REQUEST="GET_FOLLOWING_REQUEST"
export const GET_FOLLOWING_SUCCESS="GET_FOLLOWING_SUCCESS"
export const GET_FOLLOWING_FAILED="GET_FOLLOWING_FAILED"*/

export const GET_FOLLOWINGS_REQUEST="GET_FOLLOWINGS_REQUEST"
export const GET_FOLLOWINGS_SUCCESS="GET_FOLLOWINGS_SUCCESS"
export const GET_FOLLOWINGS_FAILED="GET_FOLLOWINGS_FAILED"

export const SINGLE_USER_POSTS_REQUEST="SINGLE_USER_POSTS_REQUEST"
export const SINGLE_USER_POSTS_SUCCESS="SINGLE_USER_POSTS_SUCCESS"
export const SINGLE_USER_POSTS_FAILED="SINGLE_USER_POSTS_FAILED"


export const FOLLOW_UNFOLLOW_REQUEST_SEND="FOLLOW_UNFOLLOW_REQUEST_SEND"
export const FOLLOW_UNFOLLOW_REQUEST_SUCCESS="FOLLOW_UNFOLLOW_REQUEST_SUCCESS"
export const FOLLOW_UNFOLLOW_REQUEST_FAILED="FOLLOW_UNFOLLOW_REQUEST_FAILED"


export const IS_ALREADY_FOLLOWED_REQUEST="IS_ALREADY_FOLLOWED_REQUEST"
export const IS_ALREADY_FOLLOWED_SUCCESS="IS_ALREADY_FOLLOWED_SUCCESS"
export const IS_ALREADY_FOLLOWED_FAILED="IS_ALREADY_FOLLOWED_FAILED"

export const GET_MESSAGES_REQUEST="GET_MESSAGES_REQUEST"
export const GET_MESSAGES_SUCCESS="GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_FAILED="GET_MESSAGES_FAILED"

export const SEND_MESSAGE_REQUEST="SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCES="SEND_MESSAGE_SUCCES"
export const SEND_MESSAGE_FAILED="SEND_MESSAGE_FAILED"

export const ADD_NEW_MESSAGE="ADD_NEW_MESSAGE"

export const CREATE_STORY_REQUEST="CREATE_STORY_REQUEST"
export const CREATE_STORY_SUCCESS="CREATE_STORY_SUCCESS"
export const CREATE_STORY_FAILED="CREATE_STORY_FAILED"

export const GET_STORIES_REQUEST="GET_STORIES_REQUEST"
export const GET_STORIES_SUCCESS="GET_STORIES_SUCCESS"
export const GET_STORIES_FAILED="GET_STORIES_FAILED"
